apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jlp20xtlm-go 
  janus-idp.io/tekton: jlp20xtlm-go
  backstage.io/kubernetes-id: jlp20xtlm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jlp20xtlm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  