apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jlp20xtlm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jlp20xtlm-go 
  name: jlp20xtlm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jlp20xtlm-go 
